name: CI

on:
  push:
    branches: [ feature/build_pipeline ]
  pull_request:
    branches: [ feature/build_pipeline ]

env:
  LLVM_RELEASE_VERSION: 16

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      # abort runners if a single one fails
      fail-fast: true
      matrix:
        build_type: [ Debug ]
        llvm_version: [ 16 ]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install VirtualBox
      run: |
        sudo apt-get update
        sudo apt-get install -y virtualbox

    - name: Install Vagrant
      run: |
        curl -O https://releases.hashicorp.com/vagrant/2.3.7/vagrant_2.3.7-1_amd64.deb
        sudo dpkg -i vagrant_2.3.7-1_amd64.deb

    - name: Install Packer
      run: |
        curl -L https://releases.hashicorp.com/packer/1.9.4/packer_1.9.4_linux_amd64.zip -o packer.zip
        unzip packer.zip
        sudo mv packer /usr/local/bin/

    - name: Run build
      run: |
        cd build && vagrant up
